.Dd January 30, 1988
.Dt CV 7
.Os


.Sh NAME
.Nm Emil Falk
.Nd Backend Developer


.Sh ABOUT
Backend Developer with focus on functional languages. Professional experience writing API:s for e-commerce in Erlang. Comfortable in an UNIX environment. Tries to never leave the terminal. Well rounded, curious and intrested in most things computing from semi-conductors, operating systems, networks to functional programming, IT security and algorithms.


.Sh SKILLS

.Ss languages
Erlang, SQL, awk, sh, PHP, JavaScript

.Ss protocols
DNS, HTTP, TLS

.Ss infrastructure
MySQL, nginx, HAProxy, munin, RabbitMQ, Elasticsearch, systemd, syslog

.Ss tooling
UNIX, vi, ssh, git, curl, jq


.Sh WORK

.Ss Backend Developer, Textalk, 2017-
A more senior role has brought with it more responsibility for developing, maintaining and operating all Erlang services. Additionally I have started to do more operations which meant I learnt to use some important infrastructure components such as HAProxy, nginx, munin, systemd and syslog.

.Ss Backend Developer, Textalk, 2013-2016
Started by converting existing PHP API:s to Erlang. These have over the years been extended and more has been developed. They interfaced to auxilliary systems including MySQL, RabbitMQ and Elasticsearch.
Wrote a renderer in Erlang for our single-page app which was dependent on customers themes and settings. This meant solving some intresting problems such as versioning constraints, caching and efficient template rendering.
This was backed by a file service in Erlang that served all frontend assets, both static and dynamic. New components and versions were published via internal API:s, operations that nedded to preprocess the assets (minify, concatenate, compress).



.Sh EDUCATION

.Ss Chalmers University of Technology, 2007-2013
.Bl -dash
.It
Bachelor's degree in Computer Science, 2007-2010
.It
Master in Programming Languages, Logic And Algorithms, 2010-
.It
Master in Networks and Distributed Systems, 2012-
.El

.Ss Hulebäcksgymnasiet, 2005-2007
.Bl -dash
.It
IT/Data, 2005-2007
.El


.Sh LINKS
.Bl -dash
.It
.Lk https://emfa.nu homepage
.It
.Lk https://github.com/emfa github
.It
.Lk https://www.linkedin.com/in/emil-falk-978600192 linkedin
.El


.Sh CONTACT
.Bl -dash
.It
.Lk mailto:emfa@emfa.nu email
.It
.Lk tel:+46-727-377028 phone
.El
