.Dd $Mdocdate$
.Dt CV 7
.Os


.Sh NAME
.Nm Emil Falk
.Nd Backend Developer


.Sh ABOUT
Backend Developer with focus on functional languages and databases. Professional experience writing APIs for e-commerce in Erlang. Comfortable in an UNIX environment. Tries to never leave the terminal. Well rounded, curious and intrested in most things regarding computing be it semi-conductors, operating systems or networks too high level functional programming, IT security or algorithms.


.Sh SKILLS

.Ss languages
Erlang, SQL, awk, sh, PHP, JavaScript

.Ss protocols
DNS, HTTP, TLS

.Ss infrastructure
MySQL, nginx, HAProxy, RabbitMQ, Elasticsearch

.Ss tooling
UNIX, vi, ssh, git


.Sh WORK

.Ss Junior Backend Developer, Textalk, 2013-2016
Started as junior developer helping to rewrite existing PHP API:s to Erlang. These have over the years been extended and more has been developed. A part from the MySQL database the backend interfaces to alot of auxillary systems such as RabbitMQ and ElasticSearch.
I was wrote a first-stage render that pieced together the single-page app served to customers depending on different themes and settings. This meant solving intresting problems such as versioning constraints of different components, caching in redis and efficient mustache template rendering. Along side I developed a file service for all frontend assets. It served both static and some dynamic such as a compiled SASS files. Frontend used this via internal API's for publishing new components and versions, operations that that did alot preprocessing such as minifing, concatenating and compressing the assets.

.Ss Senior Backend Developer, Textalk, 2017-
As a Senior Backend Developer I've gotten more responsibility for developing, maintaining and operating all Erlang parts in the platform. Additionally I've started to do alot more operations which meant I've learnt to use some important infrastructure components such as HAProxy, nginx, munin, systemd and syslog.


.Sh EDUCATION

.Ss Hulebäcksgymnasiet
.Bl -type dash
.It
IT/Data, 2005-2007
.El

.Ss Chalmers University of Technology
.Bl -type dash
.It
Bachelor's degree in Computer Science, 2007-2010
.It
Master in Programming Languages, Logic And Algorithms, 2010-
.It
Master in Networks and Distributed Systems, 2012-
.El


.Sh LINKS
.Bl -type dash
.It
.Lk https://emfa.nu homepage
.It
.Lk https://github.com/emfa github
.It
.Lk https://www.linkedin.com/in/emil-falk-978600192 linkedin
.El


.Sh CONTACT
.Bl -type dash
.It
.Lk mailto:emfa@emfa.nu email
.It
.Lk tel:+46-727-377028 phone
.El
